apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: marketing
  namespace: marketing
spec:
  secretName: marketing
  issuerRef:
    name: acme-issuer
    kind: ClusterIssuer
  dnsNames:
    - "marketing.trueberryless.org"
